lab06/lab06/urls.py
from django.contrib import admin
from django.urls  import include, path

urlpatterns = [
    path('tienda/', include('tienda.urls')),
    path('admin/', admin.site.urls),
]

lab06/tienda/urls.py
from django.urls import path

from . import views

app_name = 'tienda'

urlpatterns = [
    path('', views.index, name='index'),
    path('producto/<int:producto_id>/', views.producto, name='producto'),
    path('categorias/', views.categorias, name='categorias'),  
    path('categorias/<int:categoria_id>/', views.productos_por_categoria, name='productos_por_categoria'),  # Nueva URL para listar productos por categoría
]

lab06/tienda/models.py
from django.db import models

class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    pub_date = models.DateTimeField('fecha de registro',auto_now=True)
    
    def __str__(self):
        return self.nombre
class Producto(models.Model):
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE)
    nombre = models.CharField(max_length=200)
    precio = models.DecimalField(max_digits=6,decimal_places=2)
    stock = models.IntegerField(default=0)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.nombre

lab06/tienda/views.py
from django.shortcuts import render
from .models import Producto, Categoria

def index(request):
    product_list = Producto.objects.order_by('nombre')[:6]
    categorias = Categoria.objects.all()  
    context = {'product_list': product_list, 'categorias': categorias}
    return render(request, 'index.html', context)

def producto(request):
    return render(request, 'producto.html')

def productos_por_categoria(request, categoria_id):
    categoria = Categoria.objects.get(pk=categoria_id)
    productos = Producto.objects.filter(categoria=categoria)
    context = {'categoria': categoria, 'productos': productos}
    return render(request, 'productos/productos_por_categoria.html', context)

lab06/tienda/templates/index.html
<h1>Inicio</h1>
{% extends "layout.html" %}
{% block content %}
<div class="row">
  <div class="col-lg-3">
    <h3>Categorías</h3>
    <ul>
      {% for categoria in categorias %}
        <li><a href="{% url 'tienda:productos_por_categoria' categoria.id %}">{{ categoria.nombre }}</a></li>
      {% endfor %}
    </ul>
  </div>
  <div class="col-lg-9">
    <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
          <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
        </div>
        <div class="carousel-item">
          <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
        </div>
        <div class="carousel-item">
          <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
    <div class="row">
      {% for prod in product_list %}
      <div class="col-lg-4 col-md-6 mb-4">
        <div class="card h-100">
          <a href="producto/{{prod.id}}/">
            <img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
          <div class="card-body">
            <h4 class="card-title">
              <a href="producto/{{ prod.id }}/">{{ prod.nombre }}</a>
            </h4>
            <h5>S/ {{ prod.precio }}</h5>
            <p class="card-text">Categoria: {{ prod.categoria.nombre }}</p>
          </div>
          <div class="card-footer">
            <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

lab06/tienda/templates/layout.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Shop Homepage</title>
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/shop.css' %}" rel="stylesheet">
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <div class="col-lg-3">
          <h1 class="my-4"> WraP Shop</h1>
          <div class="list-group">
            <a href="#" class="list-group-item">Gaseosas </a>
            <a href="#" class="list-group-item">Snacks</a>
            <a href="#" class="list-group-item">Galletas</a>
          </div>
        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

          <!-- Block Content -->
            {% block content %}{% endblock %}
          <!-- /Block Content -->
          
        </div>
        <!-- /.col-lg-9 -->

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  </body>

</html>

lab06/tienda/templates/producto.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <img src="{{ producto.imagen_url }}" alt="{{ producto.nombre }}" class="img-fluid">
    </div>
    <div class="col-md-8">
      <h1>{{ 7up 500ml }}</h1>
      <p><strong>Categoría:</strong> {{ Gaseosas }}</p>
      <p><strong>Precio:</strong> S/ {{ 1.70 }}</p>
      <p><strong>Disponibilidad en Stock:</strong> {{ 10 }} unidades</p>
 
    </div>
  </div>
</div>
{% endblock %}

lab06/tienda/templates/productos/productos_por_categoria.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
  <h1>Productos de la categoría: {{ categoria.nombre }}</h1>
  <ul>
    {% for producto in productos %}
      <li><a href="{% url 'tienda:producto' producto.id %}">{{ producto.nombre }}</a></li>
    {% endfor %}
  </ul>
</div>
{% endblock %}